

###
### 입찰 등록
POST http://localhost:8080/api/auctions/1/bids
Content-Type: application/json
Authorization: Bearer eyJ0eXBlIjoiand0IiwiYWxnIjoiSFMyNTYifQ.eyJ1c2VySWQiOjIsImlhdCI6MTc1MTIwMDE0NywiZXhwIjoyMDY2NTYwMTQ3fQ.iRr1DCdtZlu1_--DSjENedXSzLwBiL4vcjMAgTBk8hI

{
  "biddingPrice": 198000
}